name: Call Build

# https://docs.github.com/zh/actions/writing-workflows/workflow-syntax-for-github-actions
run-name: Build Matrix for UBoot

on:
  schedule:
    # Run every day at 20:00 UTC
    - cron: "0 20 * * *"
  repository_dispatch:
  workflow_dispatch:

jobs:
  uboot:
    name: ${{ matrix.workflows_inputs.device_branch }}
    uses: ./.github/workflows/build-u-boot.yml
    strategy:
      fail-fast: false
      matrix:
        runner_image: ["ubuntu-24.04"]
        workflows_inputs:
          - device_branch: "all"
    with:
      runner_image: ${{ matrix.runner_image }}
      device_branch: ${{ matrix.workflows_inputs.device_branch }}
