name: Call Build

on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          [
            {
              workflow: "build-u-boot",
              openwrt_branch: "u-boot",
              device_branch: "all",
            },
          ]
      fail-fast: false
    steps:
      - name: Trigger workflow
        id: build
        working-directory: /
        env:
          workflow: ${{ matrix.config.workflow }}
        run: |
          data='
          {
            "ref": "main",
            "inputs": {
              "openwrt_branch": "${{ matrix.config.openwrt_branch }}",
              "device_branch": "${{ matrix.config.device_branch }}"
            }
          }'
          curl -XPOST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ env.workflow }}.yml/dispatches \
          --data "$data"
