name: C++ Switch (Dev)

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      device_branch:
        description: "Select device branch"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - 360t7
          - livinet_zr-3020
          - cetron_ct3003
          - jcg_q30
          - konka_komi-a31
          - wr30u
          - imou_lc-hx3001
          - clt_r30b1
          - abt_asr3000
          - cmcc_a10
          - cmcc_rax3000m
          - cmcc_rax3000m-emmc
          - h3c_magic-nx30-pro
          - ax3000t
          - redmi_ax6000
          - tplink_tl-xdr608x
          - ruijie_rg-x60-pro
          - jdcloud_re-cp-03
          - glinet_gl-mt6000
          - nokia_ea0326gmp
          - ruijie_rg_x30e
          - ruijie_rg_x30e_pro
          - tplink_tl-xtr8488
          - newland_nl-wr8103
          - honor_fur-602
          - newland_nl-wr9103
          - cmcc_xr30
          - cmcc_xr30-emmc
          - zyxel-ex5700
      custom_env:
        description: "key=value;key=value"
        type: string
        required: false
        default: ""

run-name: C++ Switch (Dev)

env:
  device_branch: ${{ inputs.device_branch || 'all' }}
  custom_env: ${{ inputs.custom_env || '' }}

jobs:
  build:
    name: C++ Switch (Dev)
    runs-on: ubuntu-24.04
    env:
      app_branch: "uboot"
    steps:
      - name: Set environment variable - ${{ env.device_branch }}
        id: var
        if: ${{ 'true' == 'false' }} # disable
        working-directory: /
        run: |
          echo -e "Current working directory: $(pwd)"

          # ========== Set repo branch ==========
          repo_target="https://github.com/hanwckf/bl-mt798x"
          repo_target_branch="master"
          repo_diy="https://github.com/$GITHUB_REPOSITORY"

          # ========== Build Path ==========
          dir_build="builder"
          dir_output="output"
          dir_backup="backup"
          dir_diy="DIY"
          # ---------- / ----------
          path_build="/${dir_build}"
          path_target="${path_build}/${app_branch}"
          path_output="${path_build}/${dir_output}"
          path_backup="${path_build}/${dir_backup}"

          path_diy="${path_build}/${dir_diy}"
          # release_md="${path_build}/release.md"

          # ========== GITHUB_ENV ==========
          env_vars=(
            "repo_target"
            "repo_target_branch"
            "repo_diy"
            "path_build"
            "path_target"
            "path_output"
            "path_backup"
            "path_diy"
          )
          # "release_md"
          for var in "${env_vars[@]}"; do
            echo "${var}=${!var}" | tee -a $GITHUB_ENV
          done

          echo "status=success" | tee -a ${GITHUB_OUTPUT}

      - name: Load Custom Environment Variables
        id: env-custom
        if: ${{ env.custom_env != '' }}
        env:
          flag_split: ";"
        working-directory: /
        run: |
          echo "${{ env.custom_env }}" | tr '${{ env.flag_split }}' '\n' | tee -a $GITHUB_ENV

      - name: Switch GNU C++ Version
        id: gcc
        # if: ${{ 'true' == 'false' }} # disable
        env:
          DEBIAN_FRONTEND: noninteractive
          selected_version: 14
        working-directory: /
        run: |
          packages_install=(
            "gcc-${selected_version}"
            "g++-${selected_version}"
            "gcc-${selected_version}-multilib"
            "g++-${selected_version}-multilib"
          )
          packages_extra=(
            "gcc-${selected_version}-aarch64-linux-gnu"
          )
          sudo -E apt-get -y -qq update
          sudo -E apt-get -y -qq install "${packages_install[@]}"
          sudo -E apt-get -y -qq install "${packages_extra[@]}"
          sudo -E systemctl daemon-reload

          # List GCC version
          ls /usr/bin/gcc-*
          ls /usr/bin/g++-*

          # Setup update-alternatives for GCC
          gcc_version=$(ls /usr/bin/gcc-* | grep -oP '(?<=gcc-)\d+' | sort -u)
          echo "Available GCC Version: ${gcc_version}"
          for version in ${gcc_version}; do
            if [ -f /usr/bin/gcc-${version} ]; then
              sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${version} ${version}
            fi
            if [ -f /usr/bin/gcc-ar-${version} ]; then
              sudo update-alternatives --install /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-${version} ${version}
            fi
            if [ -f /usr/bin/gcc-nm-${version} ]; then
              sudo update-alternatives --install /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-${version} ${version}
            fi
            if [ -f /usr/bin/gcc-ranlib-${version} ]; then
              sudo update-alternatives --install /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-${version} ${version}
            fi
            if [ -f /usr/bin/gcc-${version}-aarch64-linux-gnu ]; then
              sudo update-alternatives --install /usr/bin/gcc-aarch64-linux-gnu gcc-aarch64-linux-gnu /usr/bin/gcc-${selected_version}-aarch64-linux-gnu ${version}
            fi
          done
          sudo update-alternatives --query gcc

          # Setup update-alternatives for G++
          gpp_versions=$(ls /usr/bin/g++-* | grep -Eo '[0-9]+$' | sort -u)
          echo "Available G++ versions: ${gpp_versions}"
          for version in ${gpp_versions}; do
            if [ -f /usr/bin/g++-${version} ]; then
              sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${version} ${version}
            fi
          done
          sudo update-alternatives --query g++

          # Switch to selected version
          sudo update-alternatives --set gcc /usr/bin/gcc-${selected_version}
          sudo update-alternatives --set gcc-ar /usr/bin/gcc-ar-${selected_version}
          sudo update-alternatives --set gcc-nm /usr/bin/gcc-nm-${selected_version}
          sudo update-alternatives --set gcc-ranlib /usr/bin/gcc-ranlib-${selected_version}
          sudo update-alternatives --set gcc-aarch64-linux-gnu /usr/bin/gcc-${selected_version}-aarch64-linux-gnu
          # G++
          sudo update-alternatives --set g++ /usr/bin/g++-${selected_version}
          echo "Switched to GCC/G++ version ${selected_version}."

          gcc --version
          g++ --version

          # echo "CC=gcc-${{ env.GCC_version }}" | tee -a $GITHUB_ENV
          # echo "CXX=g++-${{ env.GCC_version }}" | tee -a $GITHUB_ENV

          echo "status=success" >> ${GITHUB_OUTPUT}
