name: C++ Switch (Dev)

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      device_branch:
        description: "Select device branch"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - 360t7
          - livinet_zr-3020
          - cetron_ct3003
          - jcg_q30
          - konka_komi-a31
          - wr30u
          - imou_lc-hx3001
          - clt_r30b1
          - abt_asr3000
          - cmcc_a10
          - cmcc_rax3000m
          - cmcc_rax3000m-emmc
          - h3c_magic-nx30-pro
          - ax3000t
          - redmi_ax6000
          - tplink_tl-xdr608x
          - ruijie_rg-x60-pro
          - jdcloud_re-cp-03
          - glinet_gl-mt6000
          - nokia_ea0326gmp
          - ruijie_rg_x30e
          - ruijie_rg_x30e_pro
          - tplink_tl-xtr8488
          - newland_nl-wr8103
          - honor_fur-602
          - newland_nl-wr9103
          - cmcc_xr30
          - cmcc_xr30-emmc
          - zyxel-ex5700
      custom_env:
        description: "key=value;key=value"
        type: string
        required: false
        default: ""

run-name: C++ Switch (Dev)

env:
  device_branch: ${{ inputs.device_branch || 'all' }}
  custom_env: ${{ inputs.custom_env || '' }}

jobs:
  build:
    name: C++ Switch (Dev)
    runs-on: ubuntu-24.04
    env:
      app_branch: "uboot"
    steps:
      - name: Set environment variable - ${{ env.device_branch }}
        id: var
        if: ${{ 'true' == 'false' }} # disable
        working-directory: /
        run: |
          echo -e "Current working directory: $(pwd)"

          # ========== Set repo branch ==========
          repo_target="https://github.com/hanwckf/bl-mt798x"
          repo_target_branch="master"
          repo_diy="https://github.com/$GITHUB_REPOSITORY"

          # ========== Build Path ==========
          dir_build="builder"
          dir_output="output"
          dir_backup="backup"
          dir_diy="DIY"
          # ---------- / ----------
          path_build="/${dir_build}"
          path_target="${path_build}/${app_branch}"
          path_output="${path_build}/${dir_output}"
          path_backup="${path_build}/${dir_backup}"

          path_diy="${path_build}/${dir_diy}"
          # release_md="${path_build}/release.md"

          # ========== GITHUB_ENV ==========
          env_vars=(
            "repo_target"
            "repo_target_branch"
            "repo_diy"
            "path_build"
            "path_target"
            "path_output"
            "path_backup"
            "path_diy"
          )
          # "release_md"
          for var in "${env_vars[@]}"; do
            echo "${var}=${!var}" | tee -a $GITHUB_ENV
          done

          echo "status=success" | tee -a ${GITHUB_OUTPUT}

      - name: Load Custom Environment Variables
        id: env-custom
        if: ${{ env.custom_env != '' }}
        env:
          flag_split: ";"
        working-directory: /
        run: |
          echo "${{ env.custom_env }}" | tr '${{ env.flag_split }}' '\n' | tee -a $GITHUB_ENV

      - name: Switch GNU C++ Version
        id: gcc
        # if: ${{ 'true' == 'false' }} # disable
        env:
          DEBIAN_FRONTEND: noninteractive
          GCC_version: "14"
        working-directory: /
        run: |
          echo -e "Current working directory: $(pwd)"
          set -x

          echo "CC=gcc-${{ env.GCC_version }}" | tee -a $GITHUB_ENV
          echo "CXX=g++-${{ env.GCC_version }}" | tee -a $GITHUB_ENV

          gcc --version
          g++ --version

          echo "status=success" | tee -a ${GITHUB_OUTPUT}
